sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 18302890615

  redis:
      host: localhost
      port: 6379
      password: null
      database: 0

  wechat:
    appid: wxac4c7b7a80375f94
    secret: c375f0b596ddea56e782d2b5a76a4306
